### ISSUE TITLE
Upload problem on Windows Server

### ISSUE THREAD

**Issue by nanasess** [10up/windows-azure-storage#107]
**Describe the bug**

Upload problem on Windows Server.
The following upload url is registered.
`https://containername.blob.core.windows.net/images/D:\home\site\wwwroot/wp-content/uploads/2019/11/image.png`

should be:
`https://containername.blob.core.windows.net/images/2019/11/image.png`

**Steps to Reproduce**

1. Install WordPress on Windows Server.
2. Install this plugin.
3. Upload image to Media Library.

**Expected behavior**

File upload is possible on Windows.

**Screenshots**

<img width="1323" alt="スクリーンショット 2019-11-24 21 18 51" src="https://user-images.githubusercontent.com/815715/69494513-09f9bd80-0f00-11ea-9193-df4d2ecd05cc.png">

**Environment information**
 - Server: Windows NT RD0003FF478ED3 10.0 build 14393 (Windows Server 2016) i586 (Microsoft Azure WebApps)
 - OS: MacOS 10.15.1
 - Browser and version: Safari 13.0.3
 - Plugins and version: 4.3.0
 - Theme and version: Twenty Seventeen 2.2

**Additional context**

**Comment by dlx-GH** [comment]
Same here.. My existing/fresh installs on Azure App Service.. uploads fail with the above  behavior, except that backslashes are stripped, as such:

https://containername.blob.core.windows.net/images/D:homesitewwwroot/wp-content/uploads/2019/11/image.png

**Comment by jeffpaul** [comment]
@nanasess welcome to Microsoft Azure Storage, thanks for the detailed issue, and thanks for the related PR!  @dlx-GH thanks for the confirmation of the issue on your end as well.  We'll get PR #108 through review, work with you to resolve any issues we see there, and then look to get that into the next release... thanks!
