### ISSUE TITLE
Strange path is appended to Azure storage path, and upload failes as a result

### ISSUE THREAD

**Issue by lenardg** [10up/windows-azure-storage#113]
I updated to 4.3.0 version of the plugin and to WordPress 5.3.2. 
Now whenever I upload a picture, the upload completes, but the image never ends up in Blob storage. 

Upon closer inspection, WordPress thinks the file path is something like this:

`https://bloburl/container/D:homesitewwwroot/wp-content/uploads/2020/01/filename.png`

Instead of the usual

`https://bloburl/container/2020/01/filename.png`

Here **bloburl** is the Blob storage url and **container** is the configured value for the container I am using. I have been using this plugin since 2015, and it has used the URL format I named "usual" ever since. This update brought along this change. 

So it adds the prefix:

`D:homesitewwwroot/wp-content/uploads/`

Which probably is the reason for the failure. 

Environment: 
Azure App Service

**Comment by karlromanowski** [comment]
You're likely running in Windows so you'll need to wait for https://github.com/10up/windows-azure-storage/pull/111 to be merged and released.

**Comment by lenardg** [comment]
I actually patched my 4.3.0 version with the changes in #108 and now I have it working.
