### ISSUE TITLE
Uploaded files have a bad Blob type, a bad Content Type and don't upload fully

### ISSUE THREAD

**Issue by MWaser** [10up/windows-azure-storage#114]
**Describe your question**
When creating a post with images, the images do not upload fully.

Looking at them in the Microsoft Azure Storage Explorer, I note three oddities differing from what I see if I use the Storage Explorer to upload those same images.

1.  The Blob Type is Append Blob rather than Block Blob.
2.  The Content Type is text/plain rather than image/jpeg
3.  The file size is 0 rather than the correct size

Please note that I amusing version 4.1.0 of the plug-in since, as several users have noted, version 4.3 simply does not work at all.

Given that MASE uploads correctly, I'm not sure what to do.

Any help would be greatly appreciated.

TIA.

**Comment by jeffpaul** [comment]
@MWaser what version of WordPress and PHP are you using?  Also, what OS and browser and versions are you using?  This will help us attempt to replicate your issue and better triage it to find a potential solution.

**Comment by MWaser** [comment]
So . . . . 

I noticed on one of the forums (SORRY, I can’t find it again), that the current version didn’t work but that a previous version did.  

I dropped back to 4.1.1 and it is working perfectly (note: the blob type is still Append Blob but it seems to be working fine so I guess it’s not a bad Blob type contrary to my initial belief).

I am using WordPress 5.3.2 (the newest version) and PHP 7.2.

I’ve tried the newest versions of Firefox, Edge and Chrome and none worked at all with versions 4.3 – and all had the bad Content Type and didn’t upload fully with 4.1.0.

Thank you for getting back to me so quickly!

I would love to be e-mail when the next version comes out (presumably with this problem fixed).

Please let me know if there is another other information I can provide.

	Thanks!

		Mark

**Comment by jeffpaul** [comment]
Closed via #224
