### ISSUE TITLE
Image sizes not being generated/uploaded in Set Featured Image/Add Media modal

### ISSUE THREAD

**Issue by eflorea** [10up/windows-azure-storage#117]
**Describe the bug**

Adding Featured Image or inline images (Add Media) on posts that are not created in the current month the image sizes are not being generate therefor not uploaded to Azure either. This is because when uploading an image to a post, the year/month folder used to be uploaded to is the post created/published date and not the current date.

**Steps to Reproduce**

1. Create/edit a post that is created/published on a different month than current month.
2. Click on Set Featured Image
3. Upload a new image
4. The sizes are not being generated (thumbnail of upload not showing up either) and there's an infinite of ajax calls to check azure progress.

**Comment by mmcachran** [comment]
Local testing for this looks good. On the current develop branch the image sizes are not being generated properly, but testing on single site, multisite root, and multisite subsite looks good.

**Comment by XVII** [comment]
Yep this fixes the same issue I was having. Thanks for getting to the bottom of it. I couldn't figure out the pattern!

**Comment by jeffpaul** [comment]
Closed by #118
