### ISSUE TITLE
Update docs from User Guide files

### ISSUE THREAD

**Issue by jeffpaul** [10up/windows-azure-storage#120]
**Is your enhancement related to a problem? Please describe.**
I stumbled across https://github.com/10up/windows-azure-storage/blob/master/UserGuide.docx && https://github.com/10up/windows-azure-storage/blob/master/UserGuide.pdf.  These two files were current at least around version 4.2.0.  It would be good to remove the files from the repo but add their content into the docs.  Images are old and links to Microsoft azure portal are outdated (the new one is https://azure.microsoft.com/) as well.  Ideally we refresh the links/images and pull into the plugin docs.

**Describe the solution you'd like**

- [ ] add content from https://github.com/10up/windows-azure-storage/blob/master/UserGuide.docx into README.md and readme.txt
- [ ] add content from https://github.com/10up/windows-azure-storage/blob/master/UserGuide.pdf into README.md and readme.txt
- [ ] update images in README.md and readme.txt to be current
- [ ] update links in README.md and readme.txt to be current
- [ ] remove https://github.com/10up/windows-azure-storage/blob/master/UserGuide.docx && https://github.com/10up/windows-azure-storage/blob/master/UserGuide.pdf from the report

**Designs**

n/a

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by dhanendran** [comment]
@jeffpaul Looks like there is a new file already been created as [UserGuide.md](https://github.com/10up/windows-azure-storage/blob/develop/UserGuide.md) and the other files been removed. Is there anything left on this to work on?

**Comment by jeffpaul** [comment]
@dhanendran looks like that markdown file covers what's needed here, so I'll close this out, thank you!
