### ISSUE TITLE
Update Azure Blob API to Latest - 2020-04-08

### ISSUE THREAD

**Issue by rickalee** [10up/windows-azure-storage#121]
To support more advanced features of Azure Blob Storage we should update API to latest version.

Desired Features:
* Soft Delete/Undelete Blob
* Blob Batch (bulk uploading)

https://docs.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services

**Comment by thrijith** [comment]
@rickalee @jeffpaul 

- I've updated the version string as suggested, ran some test uploads via post content and media  library and it seems to be working properly.
- Just to confirm again we want the mentioned desired features to be added along with the version update as well, or is it for a different ticket?

**Comment by jeffpaul** [comment]
@thrijith based on @rickalee's original description I'd say yeah go ahead and include those additional features in the API update PR.

**Comment by thrijith** [comment]
Thanks for confirming @jeffpaul, @rickalee / @jeffpaul query on the implementation for both features

> Soft Delete/Undelete Blob

Do we want to add a setting under `Setting` > `Microsoft Azure` to enable / disable and specify number of days the media is available before permanent deletion? 

This setting would update [service](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-service-properties) properties.

If a media is set for delete what should happen to the media in WordPress context, do we still show it in media library with and indicator it will be deleted in `x` days, and allowing to [Undelete](https://docs.microsoft.com/en-us/rest/api/storageservices/undelete-blob) in the given time?


> Blob Batch (bulk uploading)

As of now we are looping through multiple blob requests to upload, checking the [remarks](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch#remarks) and [billing](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch#billing) of the Batch endpoint wanted to check if it is an improvement.

Please do correct me if I misunderstood something, thanks!

**Comment by rickalee** [comment]
@thrijith I was expecting a performance improvement from Blob Batch but it doesn't appear to be the case from a request perspective. I think we can skip for now. I see that you updated the API Version constant, should there be more updates from upstream PHP library?

https://github.com/Azure/azure-storage-php

**Comment by thrijith** [comment]
> I was expecting a performance improvement from Blob Batch but it doesn't appear to be the case from a request perspective. I think we can skip for now.

Got it.

> Should there be more updates from upstream PHP library?

@rickalee not sure about this, I checked composer to see if we have any dependencies was not aware if we used any, can you please point me to the files to check for? Thanks!

**Comment by thrijith** [comment]
@rickalee @jeffpaul 

- It seems we can't easily copy files over and make changes as we need from [Azure/azure-storage-php](https://github.com/Azure/azure-storage-php)
- I think we should move to using `composer` dependencies as we require for our operations for example https://github.com/Azure/azure-storage-php/tree/master/azure-storage-blob
- This would mean we will need to ship all dependences along with plugin to make it work and it would also help next time we want to update.
- Current way of getting containers https://github.com/10up/windows-azure-storage/blob/develop/includes/class-windows-azure-rest-api-client.php#L569-L590
- Using the library I was able to get container response like this
  ```
    $connection_string = sprintf( 
		'DefaultEndpointsProtocol=https;AccountName=%s;AccountKey=%s',
			$this->_account_name,
			$this->_access_key
		);


	$blobClient = BlobRestProxy::createBlobService( $connection_string );
	$containers = $blobClient->listContainers();
  ```
- There are some issues with dependencies, I had to modify some functions to make it work, will need to check more for a correct fix.
- We can use the functions we have as wrappers and use above library to call new methods, please let me know if that works, thanks!

**Comment by rickalee** [comment]
@thrijith Agree with your approach. Including via composer and wrapper functions will set us up for more long-term success and maintainability.
