### ISSUE TITLE
Upload image path not always correct

### ISSUE THREAD

**Issue by cally423** [10up/windows-azure-storage#122]
**Describe the bug**
Since version 4.3.1 – the path used for the upload of images is not always correct. Here's what's happening: if one "adds media" within a post, the path will use the original post creation date and put the image in the year/month folder accordingly. It should put it in the year/month folder according to the date the image was uploaded. This also leaves a gray box in the media library for that image (no image preview). This does not happen if one uploads the image directly within media library, then later adds the image to a post.

**Steps to Reproduce**

1. Take a past post (not in the current month) and "add media" to that post. 

**Expected behavior**
Notice how the path of the URL will put the image in the directory according to the original post creation date and not when you uploaded the image. It will also leave a gray box in media library.

**Comment by mingyeungs** [comment]
Also having this issue (using Wordpress 5.4.1 and Microsoft Azure Storage for WordPress 4.3.1)

**Comment by jeffpaul** [comment]
@cally423 welcome to Microsoft Azure Storage and thanks for the issue details.  I've milestoned this for our next major release and tagged it for `help wanted` in case someone's able to help craft a PR to solve this issue.

**Comment by zar69** [comment]
Hello,
I confirm a suspicious behavior around this.
Is the next release planned please?
Thanks.
Best regards.

**Comment by jeffpaul** [comment]
@zar69 the next release is not yet planned.  As for this specific issue, if you're able to work on a PR for it then I'd gladly get it through review for it to be included in the next release.

**Comment by jeffpaul** [comment]
Closed by #131.
