### ISSUE TITLE
Upload image issues with WordPress 5.5

### ISSUE THREAD

**Issue by FreuxF** [10up/windows-azure-storage#126]
When adding a new image, I only can find the original image (original size) but the others auto generated files with different size aren't in the Azure storage slot.
They are well created by WordPress, I have checked that by using the "Keep local files".
It worked almost well in 5.4 WordPress version but now, with the 5.5, every upload has trouble.

**Example**
For example, I upload image.png in WordPress and it generates 3 other images : image-150x150.png + image-300x225.png + image-800x600.png
I will only find image.png, not the other 3.

**Steps to Reproduce**
1. Go to Media
2. Add new image
3. There is a grey box, no thumbnail
4. If you check on your Azure storage slot, only the original size image is visible

**Expected behavior**
All generated image should be visible.

**Environment information**
 - WordPress version: 5.5
 - Windows-azure-storage-plugin: 4.3.1

**Comment by taylorsolomon** [comment]
We're seeing the same thing, same environment

**Comment by jeffpaul** [comment]
@FreuxF thanks for the report and @taylorsolomon thanks for the confirmation.  I've marked this as `help wanted` and milestoned this for our next minor release.  If either of you are able to contribute a PR to resolve this, then I'd gladly get this through review for our next release... thanks!

**Comment by jeffpaul** [comment]
Closed by #131.
