### ISSUE TITLE
Test against WordPress 5.6

### ISSUE THREAD

**Issue by jeffpaul** [10up/windows-azure-storage#129]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.6 is released, we'll want to test Microsoft Azure Storage to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Microsoft Azure Storage on WordPress 5.6
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [x] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by lostfields** [comment]
I'm running PHP 8 and Wordpress 5.6 and I have a issue I haven't figured out yet. Uploading files through Media menu works fine, but not if I upload the image through the Post editing window with "Featured image". It doesn't create thumbs. I will try to find out why, but wanted to mention it since I'm running the latest wordpress now.

**Comment by jeffpaul** [comment]
@lostfields are you using `develop` of this repo in case changes in the pending 4.3.2 release resolves your issue?

**Comment by ShahAaron** [comment]
I'm currently running tests on WordPress 5.6 upgrade. When I attempt to upload a media item to QBank I get the following jQuery errors output in the browser console.

jQuery.Deferred exception: wp is not defined ReferenceError: wp is not defined
Uncaught ReferenceError: wp is not defined

The errors originate from:

windows-azure-storage-admin.js & windows-azure-storage-media-browser.js

**Comment by rickalee** [comment]
@ShahAaron Not able to replicate 'wp is not defined' error? Are you using something other than Classic Editor plugin?

**Comment by jeffpaul** [comment]
Confirming here that @davidegreenwald tested the following:
> I've done some testing with Azure storage plugin `develop` branch on WP 5.6. It uploaded without error to the media library to this month's uploads folder /2021/02 and, when adding the image from inside an older post, uploaded to the old month folder 2020/04, fixing the broken functionality. I think this is the behavior we want, yeah? Is there anything else we can look at here?

This should suffice for bumping the "tested up to" version to 5.6.  I'll handle that and then look at bundling the rest of what's in `develop` for a release.
