### ISSUE TITLE
Srcset returning local media url instead of azure urls

### ISSUE THREAD

**Issue by allanchristiancarlos** [10up/windows-azure-storage#13]
Tested on WordPress Version: 4.6.1
Plugin Version: 4.0

Srcset returning local media url instead of azure urls thats why the image fails to load.

![2016-12-23_7-28-04](https://cloud.githubusercontent.com/assets/5856845/21443572/739f64a0-c8e1-11e6-93a2-5b760db8fbdd.png)

**Comment by Ritesh-patel** [comment]
@allanchristiancarlos 

Can you check with WordPress default theme and with other plugins disabled? Also can you check if any active plugin/theme using `wp_calculate_image_srcset` filter in your site?

Regards,
Ritesh

**Comment by allan23** [comment]
Hi @allanchristiancarlos,

Can you please advise?

**Comment by allan23** [comment]
One month without feedback. Closing.
