### ISSUE TITLE
Test against WordPress 5.9

### ISSUE THREAD

**Issue by jeffpaul** [10up/windows-azure-storage#135]
**Is your enhancement related to a problem? Please describe.**
Once WordPress 5.9 is released, we'll want to test Microsoft Azure Storage to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [x] test Microsoft Azure Storage on WordPress 5.9
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
Related: #129.

**Comment by jeffpaul** [comment]
Note that I'm updating this from testing against 5.8 to 5.9.

**Comment by sudip-md** [comment]
@jeffpaul @ankitguptaindia I have tested this plugin against WP 5.9 and it is working as expected.
