### ISSUE TITLE
Azure Storage for Wordpress Plugin in major need of love

### ISSUE THREAD

**Issue by sergey-shandar** [10up/windows-azure-storage#14]
Please, feel free to close the issue. I created it keep track for this one https://github.com/Azure/azure-sdk-for-php/issues/845#issuecomment-271518747

**Comment by allan23** [comment]
Hi @sergey-shandar, the plugin no longer uses the PHP SDK you have referenced. It has been rewritten to utilize the WordPress HTTP API.
