### ISSUE TITLE
Error with WP_Filesystem() in REST API Calls

### ISSUE THREAD

**Issue by junaidbhura** [10up/windows-azure-storage#143]
**Describe the bug**

The plugin fails when trying to "crop" an image within the Block Editor, causing a corrupt image.

This is because the plugin calls `WP_Filesystem()`, which, although is available in `wp-admin`, is not available during REST API calls, which the Block Editor uses for functionality like image cropping.

**Steps to Reproduce**

1. Create a fresh WordPress site
2. Install the plugin and add all details, and ensure that `Use for default upload` is checked
3. Upload an image in Media -> Add New
4. The image successfully uploads to Azure and all thumbnails are successfully created
5. Create a new post
6. Add the image to the post and publish it
7. The post is successfully created and the image shows correctly
8. Now edit the post and and "Crop" the image (screenshot below) - maybe by zooming in - and apply the crop
9. This now fails - but the user is not aware of the failure
10. If you save the post now and look at it on the front-end, you'll see a corrupt image with incorrect SRCSET values, and none of the images were uploaded to Azure

**Expected behavior**

The plugin works well with functionality in the Block Editor like cropping.

**Screenshots**
Crop the image:
<img width="391" alt="Screen Shot 2021-06-11 at 8 44 34 am" src="https://user-images.githubusercontent.com/2512525/121606346-53cdd880-ca91-11eb-94e0-19a7bf34911a.png">

**Environment information**
 - Device: MacBook Pro
 - OS: MacOS 11.4
 - Browser and version: Brave (Chromium: 91.0.4472.77)
 - WordPress version: 5.7.2

**Additional context**

**Comment by jeffpaul** [comment]
@faisal-alvi is this properly resolved in #136?

**Comment by jeffpaul** [comment]
@colegeissinger @rickalee I think this is the last item we want to ensure is in 4.4.0 unless there's anything else you think should get released alongside the API version update?

**Comment by NicoleGeissinger** [comment]
Nothing else is needed for v4.4.0 release from my end @jeffpaul

**Comment by jeffpaul** [comment]
@colegeissinger is this issue resolved by the overall API update in #136 or is work still needed on this issue?
