### ISSUE TITLE
Change Azure storage location,  need to update older images to the new location

### ISSUE THREAD

**Issue by jrmcdona** [10up/windows-azure-storage#149]
Hi All, 
I recently moved to a new clean WordPress install and when I set up the plugin I needed to use a new Azure storage location.
I backed up and restored MySQL to the new location.

However, I see images that were uploaded before migration are still tagged with the old Azure table storage and I want to change that.

These updates appear to be what is needed but it does not work:
UPDATE wp_posts SET guid = replace(guid, 'https://prodmediacdn.blob.core.windows.net','https://office-insider-media.azurefd.net') WHERE ID IN (3281)
UPDATE wp_postmeta SET meta_value = replace(meta_value, 'https://prodmediacdn.blob.core.windows.net','https://office-insider-media.azurefd.net') WHERE meta_id IN (15631,15633)

That simply makes the URL looks like a default url for some reason:  (when I revert the updates back I see the old Azure blob URL in the location)
![image](https://user-images.githubusercontent.com/4327773/144293676-726c7ece-76b7-4e92-a1bb-fb29afcf6395.png)

**Comment by rickalee** [comment]
@jrmcdona Have you updated the C NAME using MICROSOFT_AZURE_CNAME constant or setting at wp-admin/options-general.php?page=windows-azure-storage-plugin-options ?

**Comment by jrmcdona** [comment]
@rickalee  yes, it works fine for new images.  Old images they came over from the migration all show the old url.  Been unable to change the old references.   Tried in the DB but it did not work.

**Comment by rickalee** [comment]
@jrmcdona I would check the wp_postmeta tables as well and windows_azure_storage_info meta key. Those are stored as serialized array vs string so will need to perform more custom search/replace to change.

**Comment by gioamato** [comment]
@jrmcdona did you get rid of this? Same boat here. Replaced URLs and `wp_postmeta` with `windows_azure_storage_info` keys. The media gallery is broken showing `/wp-content/uploads/*` URLs.

**Comment by jrmcdona** [comment]
@gioamato  I never was able to resolve it.  I updated MySQL to the new URL but it broke it.  When I reverted the MySQL change back to the old url it was working fine again.    Was a bit strange.  Seemed like the MySQL change would have worked.

**Comment by radeno** [comment]
Data in `wp_postmeta` are serialized with PHP serialization. It is not JSON serialization. So you should update data in MySQL with PHP, not as simple SQL commands. Because it stores metadata about string size, array size and so on. When you change string, but not metadata, it will be broken.

**Comment by gioamato** [comment]
@radeno got it, thank you. For future readers, found multiple ways to do it:

1. Using `WP-CLI`, detailed instructions [here](https://dba.stackexchange.com/questions/64675/replace-string-within-serialized-data/239923#239923).
2. Directly inside WordPress, using the [Better Search Replace plugin](https://wordpress.org/plugins/better-search-replace/).
3. Using an external tool that supports serialization, like [Search Replace DB](https://github.com/interconnectit/Search-Replace-DB).

**Comment by jeffpaul** [comment]
@radeno @gioamato if either of you are able to submit some details on that for the README.md file (maybe a new FAQ section), that would be fantastic, thanks!

**Comment by gioamato** [comment]
@jeffpaul done in #163. I haven't created the new FAQ section, it would be quite empty atm.

It could be useful to collect more q&a and infos and completely restyle the `README.md` file. I would be happy to contribute and help.
