### ISSUE TITLE
Add option to populate the CacheControl header in uploads

### ISSUE THREAD

**Issue by ShadowXVII** [10up/windows-azure-storage#17]
I'd like to use a higher "max-age" in my CacheControl header for each BLOB.

Can we have a field in the Settings that gets put into the CacheControl property on upload?

**Comment by allan23** [comment]
Hi @ShadowXVII,

This is a great suggestion. We are open to pull requests to better enhance the plugin.

**Comment by eugene-manuilov** [comment]
Hey @ShadowXVII!

It has been added and published with version 4.1.0. Thanks for the suggestion! I am going to close this issue now. Feel free to open a new one if you have anything else.

**Comment by ShadowXVII** [comment]
Thanks for the update -- noticed it a few weeks ago.

Despite setting it in the options, new BLOBs don't seem to have the header set?
If I check via Storage Explorer at a recently uploaded image, it has an empty CacheControl attribute.

e.g. I'd expect it to read "public, max-age=7776000"

**Comment by eugene-manuilov** [comment]
Hm.... i'll need to look at it tomorrow.

**Comment by eugene-manuilov** [comment]
Ok, my fault... There is a bug in it... I have fixed it and added the ability to filter cache-control header for each blob as well as enter an arbitrary cache-control value into the settings. Will include it in the next release.

**Comment by jeffpaul** [comment]
@eugene-manuilov did your fix get included in a specific release or is that still pending?

**Comment by jeffpaul** [comment]
@ShadowXVII doing some spelunking on commits, it looks like this did get committed back in January 2018 (see #51).  We're working to tidy things up and get an updated release out, so you should see that in an official release in a bit.

**Comment by jeffpaul** [comment]
@ShadowXVII note that v4.3 has been released, mind testing to confirm that this issue is resolved?

**Comment by XVII** [comment]
I missed this back in 2019! Yes, my recent uploads are working fine with v4.3.1.

Regards,
Jake
