### ISSUE TITLE
Incorrect Content-Type being applied to uploaded files in v 4.4.0

### ISSUE THREAD

**Issue by okadots** [10up/windows-azure-storage#210]
### Describe the bug

When uploading files via the WP admin, the Content Type is being incorrectly applied in Azure. All files, regardless of file type, are being uploaded to Azure with the content type of `application/octet-stream`. 

In WordPress, the attachment details show the correct content type.

This is causing PDFs to automatically download vs open in the browser. This is the case for all uploaded media files as well.

Changing the content type via the Azure interface resolves the behavior issue, but manually resolving for every file uploaded to a multiuser multisite is not a reasonable workflow. 

Downgrading to v 4.3.5 fixes the issue and the correct content type is applied.

### Steps to Reproduce

1. Upload a file of any kind via WP admin
2. In the attachment details, copy the file url and paste in browser. File will download instead of being viewed in the browser.
3. To test file type, `curl -v` the file url and see that content type is: `Content-Type: application/octet-stream`

### WordPress information

Microsoft Azure Storage for WordPress v4.4.0
WordPress v6.3.1, this is a multisite
php v8.2
mysql v8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarahannnicholson** [comment]
Can I just add, that this is happening for .svg files as well. 

Microsoft Azure Storage for WordPress v4.4.0
Wordpress version: v6.4.1

**Comment by nicoladj77** [comment]
Bug confirmed for me too, with PDF uploads on v4.4.0

**Comment by hugosolar** [comment]
This should be fixed with this PR: #224
