### ISSUE TITLE
Uploading to Azure fails after second image

### ISSUE THREAD

**Issue by nasklik** [10up/windows-azure-storage#226]
### Describe your question

So I have issues when uploading more than one image at time, when I upload more than 2 photos, third photo is stuck at "uploading to the azure" 
![image](https://github.com/10up/windows-azure-storage/assets/25064249/28c67186-a95a-4814-b96d-daef41c8d4e7)

This is what shows up in the console, and I have no idea how to fix this. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nasklik** [comment]
![image](https://github.com/10up/windows-azure-storage/assets/25064249/33c71bd6-375e-482b-8f8f-598034a7c812)
This is as well, it stays like this for ages, and it does not finish uploading.

**Comment by nasklik** [comment]
![image](https://github.com/10up/windows-azure-storage/assets/25064249/b8e9a9f5-98d7-4b9c-beb0-be1ea622427c)

**Comment by nasklik** [comment]
![image](https://github.com/10up/windows-azure-storage/assets/25064249/d4b15f62-f783-41d8-a4c3-f7491bd26b36)
This is the network

**Comment by hugosolar** [comment]
@Ensismensi would you please expand the post request in your browser so I can see which error code you're getting?
also, are you able to see any error in the debug.log? 
https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/#example-wp-config-php-for-debugging
