### ISSUE TITLE
Latest releases not creating image sizes

### ISSUE THREAD

**Issue by glowmedia** [10up/windows-azure-storage#229]
### Describe the bug

EW recently noticed an issue where the plugin was only uploading the original image to azure and not creating other image sizes (thumbnails for example) so the WordPress media library shows grey squares instead of the image. We managed to get this working again by downgrading the plugin to 4.3.5 as nothing newer works

### Steps to Reproduce

1. upgrade to latest version
2. upload new image
3. check media library - grey square (no thumbnail)
4. check azure storage - only initial image uploaded no resized versions.

### Environment information

OS: Linux
Server: nginx/1.24.0
Hostname: www.xxxxxxxx.co.uk
IP:Port: 169.254.129.3:8080
Document Root: /home/site/wwwroot

PHP
v8.2.17
GD: bundled (2.1.0 compatible)
Memory Limit: 800.0 MiB
Max Script Execute Time: 60s
Max Post Size: 256.0 MiB
Max Upload Size: 256.0 MiB
MYSQL

v8.0.36
Maximum No. Connections: 1,250
Maximum Packet Size: 1,024.0 MiB
Data Disk Usage: 667.4 MiB
Index Disk Usage: 906.5 MiB

### WordPress information

`
### wp-core ###

version: 6.5.3
site_language: en_GB
user_language: en_GB
timezone: Europe/London
permalink: /%postname%
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: closed
environment_type: production
user_count: 11
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/site/wwwroot
wordpress_size: 58.60 MB (61449158 bytes)
uploads_path: /home/site/wwwroot/wp-content/uploads
uploads_size: 1.86 GB (1995996171 bytes)
themes_path: /home/site/wwwroot/wp-content/themes
themes_size: 58.60 MB (61445763 bytes)
plugins_path: /home/site/wwwroot/wp-content/plugins
plugins_size: 126.45 MB (132591136 bytes)
database_size: 1.54 GB (1650393088 bytes)
total_size: 3.63 GB (3901875316 bytes)

### wp-dropins (2) ###

advanced-cache.php: true
db.php: true

### wp-active-theme ###

name: XXXXXXXX
version: 3.6.3
parent_theme: none
theme_features: disable-custom-font-sizes, disable-custom-colors, disable-custom-gradients, align-full, editor-color-palette, editor-font-sizes, align-wide, post-thumbnails, menus, widgets-block-editor
theme_path: /home/site/wwwroot/wp-content/themes/xxxxxxxx
auto_update: Disabled

### wp-themes-inactive (6) ###

Twenty Nineteen: version: 2.8, author: WordPress Team, Auto-updates disabled
Twenty Twenty: version: 2.6, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Four: version: 1.1, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 2.2, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Three: version: 1.4, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.7, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.9.1

### wp-plugins-active (24) ###

Advanced Custom Fields PRO: version: 6.2.9, author: WP Engine, Auto-updates disabled
Advanced Editor Tools: version: 5.9.2, author: Automattic, Auto-updates disabled
Bootstrap 3 Shortcodes: version: 3.3.12, author: Michael W. Delaney, Filip Stefansson, and Simon Yeldon, Auto-updates disabled
Entry Automation for Gravity Forms: version: 5.5.0, author: CosmicGiant, Auto-updates disabled
FacetWP: version: 4.3, author: FacetWP, LLC, Auto-updates disabled
FluentSMTP: version: 2.2.73, author: FluentSMTP & WPManageNinja Team, Auto-updates disabled
Gravity Forms: version: 2.8.9, author: Gravity Forms, Auto-updates disabled
Health Check & Troubleshooting: version: 1.7.0, author: The WordPress.org community, Auto-updates disabled
Hotjar: version: 1.0.16, author: Hotjar, Auto-updates disabled
Microsoft Azure Storage for WordPress: version: 4.3.5, author: 10up, Microsoft Open Technologies (latest version: 4.4.2), Auto-updates disabled
Password Protected: version: 2.7.2, author: Password Protected, Auto-updates disabled
SearchWP: version: 4.3.15, author: SearchWP, Auto-updates disabled
Supply Chain Blocks: version: 2.0, author: Cite, Auto-updates disabled
WP-ServerInfo: version: 1.66, author: Lester 'GaMerZ' Chan, Auto-updates disabled
WP 2FA - Two-factor authentication for WordPress: version: 2.6.4, author: Melapress, Auto-updates disabled
WP All Export - ACF Export Add-On Pro: version: 1.0.5, author: Soflyy, Auto-updates disabled
WP All Export Pro: version: 1.8.8, author: Soflyy, Auto-updates disabled
WP All Import - ACF Add-On: version: 3.3.8, author: Soflyy, Auto-updates disabled
WP All Import - Yoast WordPress SEO Add-On: version: 1.1.8, author: Soflyy, Auto-updates disabled
WP All Import Pro: version: 4.8.7, author: Soflyy, Auto-updates disabled
WP Rocket: version: 3.15.10, author: WP Media, Auto-updates disabled
WPS Hide Login: version: 1.9.15.2, author: WPServeur, NicolasKulka, wpformation, Auto-updates disabled
Yoast SEO: version: 22.7, author: Team Yoast, Auto-updates disabled
Yoast SEO Premium: version: 22.0, author: Team Yoast, Auto-updates disabled

### wp-plugins-inactive (6) ###

Nginx Helper: version: 2.2.5, author: rtCamp, Auto-updates disabled
Performance Lab: version: 3.0.0, author: WordPress Performance Team, Auto-updates disabled
Query Monitor: version: 3.16.2, author: John Blackbourn, Auto-updates disabled
WP Crontrol: version: 1.16.3, author: John Blackbourn, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 98304
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.15.153.1-1.cm2 x86_64
httpd_software: nginx/1.24.0
php_version: 8.2.17 64bit
php_sapi: fpm-fcgi
max_input_variables: 7000
time_limit: 60
memory_limit: 800M
max_input_time: -1
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.74.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: true
pretty_permalinks: true
current: 2024-05-14T13:09:51+00:00
utc-time: Tuesday, 14-May-24 13:09:51 UTC
server-time: 2024-05-14T14:09:50+01:00

### wp-database ###

extension: mysqli
server_version: 8.0.36
client_version: mysqlnd 8.2.17
max_allowed_packet: 1073741824
max_connections: 1250

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/site/wwwroot/wp-content
WP_PLUGIN_DIR: /home/site/wwwroot/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 800M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@rickalee @hugosolar are y'all seeing anything similar in your usage?

**Comment by hugosolar** [comment]
@jeffpaul I'm not seeing that behavior
@glowmedia by any chance, are you seeing any error in the WP debug log?
https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/#example-wp-config-php-for-debugging

**Comment by glowmedia** [comment]
@hugosolar 

> @jeffpaul I'm not seeing that behavior @glowmedia by any chance, are you seeing any error in the WP debug log? https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/#example-wp-config-php-for-debugging

I have installed a debug plugin but there are no obvious errors shown in the log this plugin generates, a few of the errors are:

PHP Warning: Cannot modify header information - headers already sent by (output started at /home/site/wwwroot/wp-includes/functions.php:6078) in /home/site/wwwroot/wp-includes/pluggable.php on line 1438 | 1 hour ago |   | 13/06/24
-- | -- | -- | --
PHP Warning: Cannot modify header information - headers already sent by (output started at /home/site/wwwroot/wp-includes/functions.php:6078) in /home/site/wwwroot/wp-includes/pluggable.php on line 1435

PHP Warning: Cannot modify header information - headers already sent by (output started at /home/site/wwwroot/wp-includes/functions.php:6078) in /home/site/wwwroot/wp-admin/admin-header.php on line 9

PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
-- | -- | -- | --
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376



PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
-- | -- | -- | --
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376


PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
-- | -- | -- | --
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376 | 1 hour ago |   | 13/06/24
PHP Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/site/wwwroot/wp-includes/post.php on line 3376

**Comment by hugosolar** [comment]
@glowmedia our latest version ([4.4.2](https://github.com/10up/windows-azure-storage/releases/tag/4.4.2)) fixes an issue with content type not being set correctly in the block blob
would you try updating the plugin to the latest version and try the upload process again?
let me know how that goes

**Comment by glowmedia** [comment]
@hugosolar I am using the latest version of the plugin and the issue is still there, it only appears to work when using version 4.3.5, all later versions have the issue

**Comment by glowmedia** [comment]
@hugosolar after testing more and setting up an new environment, i have found out that it must be something in the very complicated theme i inherited, your plugin works fine on the standard wp themes but not ours.

**Comment by glowmedia** [comment]
@hugosolar on further testing, I set the theme to a default one and the issue was still present, so deactivated all plugins apart from yours and for some reason the issue is still there, could this be something with the environment?

**Comment by glowmedia** [comment]
Hi we have had a bit of brain wave, we have found the latest version of the plugin does work but only if you tick the 'Organise my uploads into month- and year-based folders' option. When this is unticked the issue happens. Can you let me know if there is anything that can be done so we don't have to have this option clicked? Thanks Steve

**Comment by hugosolar** [comment]
@glowmedia thank you for all the testing you've made!
I'll investigate to see if I can replicate the issue and get back to you

**Comment by glowmedia** [comment]
@hugosolar I have modifed the plugin on one of my environments with your code and the issue looks to be fixed. Thank you
