### ISSUE TITLE
Custom CNAME container name dublication in URL

### ISSUE THREAD

**Issue by Besdima** [10up/windows-azure-storage#243]
### Describe the bug

After updating the plugin, all pictures became unavailable on the site.

For some reason, it duplicated the storage container in the photo URL: 

https://cdn.besdima.dev/besdimadev/besdimadev/2021/09/Photo2.jpg

Where it should be https://cdn.besdima.dev/besdimadev/2021/09/Photo2.jpg

### Steps to Reproduce

Happened after the automatic plugin update.

To reproduce, you need to have CNAME set in settings.
Create a new post.
Upload a picture.
After publication, the picture is not available due to the wrong URL.

### Environment information

OS: Linux
Server: nginx/1.26.1
Document Root: /home/site/wwwroot
PHP - v8.3.8

### WordPress information

Current version: 6.5.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
```

**Comment by Besdima** [comment]
Workaround to fix it is to disable CNAME

**Comment by ms2oo8** [comment]
I am experiencing the same issues. Will there be a bug fix? Disabling CNAME isn't really a resolution.

**Comment by BCornelissen** [comment]
Confirm the same bug. The URL to the picture gets augmented with an additional folder name. In my case "/blog/picture.png" becomes "/blog/blog/picture.png". It did not happen to everything it seems. A number of entries were affected, but not all.
This happened with the update to 4.5.0
In WordPress, while editing the blog post and opting to edit the HTML of the picture block, I see the correct URL.
When looking at the actual blog post the picture is not displayed and the link to the picture shows the additional folder name.
