### ISSUE TITLE
foreign characters file name problems

### ISSUE THREAD

**Issue by jiji0806** [10up/windows-azure-storage#25]
Hi, can u or can I figure out line number for the sanitizing filename?
my Korean character image file got some error when I try to upload to blob storage.

I think there might be a lot of people who need to fix this problem.

could you update plugin or u can tell me the line number for that function, so that I can make it allow foreign characters file name works with this awesome plug-in.

thanks

**Comment by allan23** [comment]
Hello @jiji0806,

We never recommend directly editing the plugin when you can use filters to accomplish something. Thankfully, this plugin utilizes WordPress core functionality that can be filtered (https://developer.wordpress.org/plugins/hooks/filters/).

Looking at the plugin's codebase, you may be able to resolve your issue with one or more of the following filters:

1. Hook into the `sanitize_file_name` filter to alter the filename. (https://developer.wordpress.org/reference/hooks/sanitize_file_name/)

2. You can hook into the `wp_handle_upload` filter to see if you can encode the filename (https://developer.wordpress.org/reference/hooks/wp_handle_upload-7/).

**Comment by jiji0806** [comment]
thank you for answering me.

Wordpress itself, allows us to upload image file which contains foreign characters ( at lease Korean characters since I tested).
1.so I think "sanitize_file_name" <-  shouldn't be any problem, I checked Wordpress core function and it was about avoiding special characters.

2. next, I tried find out how to use and hook with "wp_handle_upload".
but it's not certain for me...I think I lost.

if you mind, can you write piece of code that can resolve this problem.. I will be appreciate it.
if you busy, can u guide me more detail please.
