### ISSUE TITLE
0 Byte file when 'uploads_use_yearmonth_folders' set to 0 (OFF)

### ISSUE THREAD

**Issue by jammer99** [10up/windows-azure-storage#28]
There is a minor issue when "uploads_use_yearmonth_folders" in wordpress options is set to 0. 
This particular use case is when using Wordpress multisite.
On line `445` in `windows-azure-storage.php`
```php
\Windows_Azure_Helper::put_media_to_blob_storage(
		$default_azure_storage_account_container_name,
		$blob_name,
		trailingslashit( $file_upload_dir ) . $size['file'],
		$mime_type
	);
```
the value of the 3rd param (`trailingslashit( $file_upload_dir ) . $size['file'],`) is "\myimage-150x150.png" which causes the upload to return false.
This can be replaced with 
```php
\Windows_Azure_Helper::put_media_to_blob_storage(
		$default_azure_storage_account_container_name,
		$blob_name,
		$blob_name,
		$mime_type
	);
```
to get rid of this issue. 

I would like to know why was `trailingslashit( $file_upload_dir ) . $size['file']` added when on line 411 on the same file `$relative_file_name` is used for both the parameters.

:)

**Comment by allan23** [comment]
Hi @jammer99, that you for submitting this issue. 
Are you using the latest version of the plugin and the latest version of WordPress?

**Comment by jammer99** [comment]
I am using the latest versions 
Wordpress 4.8 and windows azure storage plugin 4.0.2

**Comment by jammer99** [comment]
Is there no update on this?

**Comment by kdlarson** [comment]
This is still an issue with Wordpress 4.8.2 and plugin 4.0.2. I am not running Multisite,

**Comment by eugene-manuilov** [comment]
Hi @jammer99 and @kdlarson,

recently we release a new version of this plugin which contains a few fixes that may affect and resolve your issue. Could you please install version 4.0.3 on your sites and let me know if you still see your issues?

**Comment by jammer99** [comment]
This issue seems to be fixed in the latest plugin release. Thanks for fixing this. 💯
