### ISSUE TITLE
Srcset not generating correct urls when using CNAME

### ISSUE THREAD

**Issue by kdlarson** [10up/windows-azure-storage#30]
Same issue as closed #13 (was closed for non-activity). When using CNAME to Azure CDN (storage origin), the srcset paths are generated with the default WP relative path of "/wp-content/uploads" rather than the cdn path. This happens in the WP default theme.

The browser then tries to fetch the image using the CDN endpoint + incorrect relative path + blob name (e.g. "https://cdn.azureedge.net/wp-content/uploads/blob.jpg" which in my case should be "https://cdn.azureedge.net/media/blob.jpg"). 

Thanks!

**Comment by tott** [comment]
Hi,

we're going to have a look at this issue and will let you know if we need any further feedback from you.

Thanks
         Thorsten

**Comment by eugene-manuilov** [comment]
Hi @kdlarson,

I have checked it on my local and it works correctly. Could you please tell me what theme do you use and if there any other plugin activated?

**Comment by kdlarson** [comment]
I created a vanilla WordPress install on Azure with only the Window Azure Storage plugin activated and using the default Twenty Seventeen theme.

In the default configuration, everything works -- both storage and cdn work perfectly. 

But when I uncheck the option for WordPress to store media in year/month folder structure (Settings - Media - Organize my uploads into month- and year-based folders), I see the following two bugs: 

1. Responsive image versions stored with **zero bytes** (original file stored correctly)
2. Anywhere the uploaded image is used, **srcset does not include cdn path** (see below)

Image Stored using year/month folders:

`
<img width="233" height="300" class="alignnone size-medium wp-image-4" alt="" src="https://schoolerz-media-test2.azureedge.net/media/2017/10/Big_buck_bunny_poster_big-233x300.jpg" srcset="https://schoolerz-media-test2.azureedge.net/media/2017/10/Big_buck_bunny_poster_big-233x300.jpg 233w, https://schoolerz-media-test2.azureedge.net/media/2017/10/Big_buck_bunny_poster_big-768x990.jpg 768w, https://schoolerz-media-test2.azureedge.net/media/2017/10/Big_buck_bunny_poster_big-794x1024.jpg 794w" sizes="(max-width: 233px) 100vw, 233px">
`

Image stored with "Organize my uploads into month- and year-based folders" unchecked:
`
<img width="233" height="300" class="alignnone size-medium wp-image-6" alt="" src="https://schoolerz-media-test2.azureedge.net/media/sintel_poster-233x300.jpg" srcset="/wp-content/uploads/sintel_poster-233x300.jpg 233w, /wp-content/uploads/sintel_poster-768x990.jpg 768w, /wp-content/uploads/sintel_poster-794x1024.jpg 794w, /wp-content/uploads/sintel_poster.jpg 993w" sizes="(max-width: 233px) 100vw, 233px">
`

Thanks for taking a look at this, and for the great plugin.

**Comment by eugene-manuilov** [comment]
Thanks, @kdlarson! It helped a lot. I have fixed these issues and created a new pre-release (4.0.3). Could you please try it on your setup and let us know if it helps you or not? Thanks in advance!

https://github.com/10up/windows-azure-storage/releases

**Comment by kdlarson** [comment]
Great job, @eugene-manuilov! In my testing, all features work perfectly. I tested it in both my basic vanilla WP install and also in my heavy and complex "real" site. Thanks very much for fixing this so quickly.
