### ISSUE TITLE
Zero Byte Uploads

### ISSUE THREAD

**Issue by techietrev** [10up/windows-azure-storage#38]
When uploading non-image files (sound or video files, 599 KB m4a file for example) to WordPress media library, we find that a few seconds after the file is uploaded it is no longer playable. If we try to play immediately from media library after upload done, it plays fine, but if we revisit file a few seconds later and try to open/play, it no longer plays. In background we find that file gets set to zero bytes and remains in blob store showing that size and non-playable at that point..
Environment: Clean install of WordPress 4.8.2 for testing this issue in clean environment, with plugin version 4.0.3 and the default WordPress twenty-seventeen theme. No other plugins activated and no customizations existing in site in any way. Only this plugin configured for testing this issue. Can you please look into for us.

**Comment by eugene-manuilov** [comment]
Hi @techietrev,

i have tried to replicate it on my end and it works for me. Can you share your audio file with me?

**Comment by techietrev** [comment]
Noticed you have a Ver 4.1.0 update to your plugin.  Updated our test site to see if that remedied issue and then re-uploaded the test file above.  Still same situation.  File plays at first at time of upload, but a few seconds later will not play anymore.  Assume file is getting zero'd out still.

**Comment by jpaarhuis** [comment]
I'm having a Pull Request for this issue already. Hope it will come through in the next days: https://github.com/10up/windows-azure-storage/pull/23

**Comment by eugene-manuilov** [comment]
Hm... still can't replicate that... it loads properly on my end even with your file: https://tenuptest.blob.core.windows.net/10up/2017/11/Remembrance-Day-Peace-Song.m4a?_=1

Do other files and file types have the same issue or just this file? Can you try to upload an image, a video and another audio file?

**Comment by techietrev** [comment]
Question, do you have any documents that would help in re-internalizing our blob data back into WordPress for moving back to on-premise hosting?

**Comment by twDuke** [comment]
I have the same problem, seems to be that the plugin cant get access to wp filesystem. 
The call to WP_Filesystem fails in get_provider, even though i have chmod 777 to the upload path for testing, and chown for whole wp-content to www-data user.

**Comment by techietrev** [comment]
Version on this site seems to fix issue for us.  Thanks.

**Comment by eugene-manuilov** [comment]
Ok, great! Thanks for the confirmation.

**Comment by lmmartinm** [comment]
Hello

I can confirm the bug. It occurs using "/wp-admin/upload.php" URL, but if instead you use "/wp-admin/media-new.php" URL for uploading no images media, seems to work.

@techietrev which version woks for you?

Thank you
