### ISSUE TITLE
Unicode file name support

### ISSUE THREAD

**Issue by radeno** [10up/windows-azure-storage#59]
Hello,

based on this issue opened on WP support forum https://wordpress.org/support/topic/non-encoded-urls/ plugin can't handle properly with paths / filenames / directories with unicode characters.

Tested on slovak characters. Adding php function `urlencode` helps.
I don't open any PR, because I can't say if exists any other code parts, where url encoding is required.

This document https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#resource-names says, in Important block, that all names with certain characters should be percent-encoded. Don't know what certain characters are, but `urlencode` helps.

Maybe there is better way how to fix it.

**Comment by allan23** [comment]
This looks like it could be resolved via PR: #61
