### ISSUE TITLE
Release 4.2.0

### ISSUE THREAD

**Issue by radeno** [10up/windows-azure-storage#67]
Hello,

any chance to publish version 4.2 early ?

In master is very necessary fix for uploading files with unicode naming, not just ASCII.
And version 4.2 brings very handy settings by constants, very nice feature for containerised deployment.

**Comment by oscarssanchez** [comment]
Hi @radeno ,

Thanks for raising your concern. We definitely have plans to release 4.2 to wp.org soon. We just have to run some QA and update the readme files :) 

Thanks again, and hope you have a great day!

**Comment by radeno** [comment]
@oscarssanchez four months ahead. Still no release? :/

**Comment by allan23** [comment]
Hello @radeno, would you be able to run some tests on the `master` branch for the 4.2.0 release?

**Comment by radeno** [comment]
Hi, @allan23, what king of tests do you mean? I should test it on staging Azure Storage if you want.
Some basic testing scenarios for uploading and removing.

**Comment by allan23** [comment]
Yep. That would be great.

**Comment by radeno** [comment]
@jeffpaul not yet. I wanna today. @allan23 which branch is actual, master or release 4.2.0 ?

**Comment by radeno** [comment]
Looks like it works!

**Comment by jeffpaul** [comment]
@radeno which branch did you test?

**Comment by radeno** [comment]
4.2.0

**Comment by jeffpaul** [comment]
@allan23 any other items before merging that release branch and tagging the 4.2.0 release officially here in GitHub?  https://github.com/10up/windows-azure-storage/tree/release/4.2.0

**Comment by radeno** [comment]
Will be released sometimes ?

**Comment by jeffpaul** [comment]
@oscarssanchez do you have any background on the [4.2.0 release]( https://github.com/10up/windows-azure-storage/tree/release/4.2.0) and whether anything additional is needed before merging the release branch and tagging the 4.2.0 release officially here in GitHub?

**Comment by radeno** [comment]
Any news?

**Comment by jeffpaul** [comment]
@radeno the plan is to focus on the 4.3 release and work to properly tag/release that when its ready.

**Comment by jeffpaul** [comment]
My current thinking is to merge the [4.2 release branch](https://github.com/10up/windows-azure-storage/tree/release/4.2.0) into `develop` and then `develop` into `master`, resolving conflicts along the way.  Then looking to review and merge open and viable PRs to `develop` and then merge that to `master` as 4.3.  Thoughts?

**Comment by oscarssanchez** [comment]
Sounds good to me @jeffpaul

**Comment by jeffpaul** [comment]
Note that progress was made today towards getting the branches/etc. in proper order and towards getting a new release that includes all updates to date plus a fix for #92.

**Comment by jeffpaul** [comment]
Note that v4.3 has been released, so I'll close this issue as resolved: https://github.com/10up/windows-azure-storage/releases/tag/4.3.0
