### ISSUE TITLE
Srcset returning the wrong url when using crop thumbnail plugin

### ISSUE THREAD

**Issue by Keomoniroath** [10up/windows-azure-storage#72]
Hello, 

When I cropped an image the srcset url isn't azure storage url only for WP native image size such as the thumbnail. You can have an exemple at the bottom of the post in the section "Découvrez également" : https://experiences.microsoft.fr/business/new-culture-of-work-business/linnovation-appelle-un-equilibre-entre-ambition-et-humilite-nicolas-marry-avanade/

Once the image is cropped, the srcset url change to "https://experiences.microsoft.fr/wp-content/uploads/..."
and it should be "https://experienceswp.blob.core.windows.net/uploads/..."

I also opened an issue at Crop Thumbnail GitHub if you want more details, they say it may be a synchronization problem from Azure Storage : https://github.com/vollyimnetz/crop-thumbnails/issues/29

The problem persist for every crop plugin used.

**Comment by oscarssanchez** [comment]
Hi @Keomoniroath , sorry for late reply.

Unfortunately i have not been able to correctly show the cropped image with or without Azure activated/installed, would you mind providing some guidance/steps on how to use this plugin to be able to reproduce this issue? 

Also, If for some reason, the crop plugin requires thumbnail regeneration, can you try regenerating the thumbnails via WP CLI ?

Thanks!

**Comment by Keomoniroath** [comment]
Hello @oscarssanchez, thanks for your reply.

For the crop plugin i just installed it and start to crop image of a post and save it :
![image](https://user-images.githubusercontent.com/29626942/54523557-1d678880-4970-11e9-819c-383ab9eb3960.png)![image](https://user-images.githubusercontent.com/29626942/54523636-3d974780-4970-11e9-93cf-8ae50f0b45c7.png)

But here an exemple when Azure Storage is activated :
![image](https://user-images.githubusercontent.com/29626942/54523803-a7afec80-4970-11e9-91bb-cf1a8bc1edbe.png)

All the customs image size add in functions.php is displayed but not WP native image size.
When I use WP CLI I have to crop the image again and it's the same result, the thumbnail is not displayed.

**Comment by oscarssanchez** [comment]
Hi @Keomoniroath ,

This is what I'm currently doing: 
https://youtu.be/R17wv6FgJWE

Am I doing something wrong here?

**Comment by jeffpaul** [comment]
@Keomoniroath any feedback from Oscar's response above?

**Comment by Keomoniroath** [comment]
Hello @oscarssanchez, sorry for my late answer.

I don't see anything wrong, if you try to display the thumbnail size after crop does it show in front ?
What i'm doing to reproduce the bug : https://youtu.be/RuB3VIquQWk

Do you think it's related to the environment or something else ? I try to desactivate  all the other plugin except crop thumbnail and the issue still here.

Thanks !

**Comment by oscarssanchez** [comment]
Hi @Keomoniroath ,

It does show on front, but without my cropping changes, i think that is not the right behavior?

**Comment by jeffpaul** [comment]
@Keomoniroath any response to Oscar's update above?

**Comment by Keomoniroath** [comment]
Hi @oscarssanchez,

Sorry for my late reply, finally we will remove this feature from our website.
Thanks a lot for your time, will be back with more details if we decide to implement it again.
