### ISSUE TITLE
Allow settings for Azure to be defined in wp-config.php rather than in database

### ISSUE THREAD

**Issue by TheLastCicada** [10up/windows-azure-storage#88]
When dynamically setting the Azure Storage locations when creating new sites, it is helpful to be able to hard-code these things (like the storage key, storage account name, and container name) in wp-config.php rather than as options in the database.  There are also big security benefits of doing this as an attacker can't get access to a WordPress admin user and change where uploads serve from, which would allow them to serve malicious files from a location they control.  Many other plugins that link WP to an object storage systems use this method to set the variables, such as https://github.com/humanmade/S3-Uploads.

**Comment by radeno** [comment]
@TheLastCicada version 4.2 allows this. But it isn't released yet.

**Comment by jeffpaul** [comment]
@TheLastCicada @radeno note that v4.3 has been released, mind testing to confirm that this issue is resolved?

**Comment by radeno** [comment]
Everything works in the same way after creating constants and removing settings from database. GJ 👍

**Comment by jeffpaul** [comment]
Thanks for the confirmation @radeno, I'm going to close this as resolved but happy to re-open if folks find any issues with the implementation that shipped in v4.3.
