### ISSUE TITLE
Ambiguity around crucial element of settings page

### ISSUE THREAD

**Issue by johnwatkins0** [10up/windows-azure-storage#90]
**Is your enhancement related to a problem? Please describe.**

I have low familiarity with this plugin and am attempting to use it for the first time. In getting set up, I come across the following setting:

<img width="1245" alt="Screen Shot 2019-10-24 at 9 50 12 PM" src="https://user-images.githubusercontent.com/9020968/67539634-5a36f300-f6a8-11e9-90a6-962eaaa8661e.png">

> Use for default upload | Use Microsoft Azure Storage when uploading via WordPress' upload tab.Note: Uncheck this to revert back to using your own web host for storage at anytime. You can define MICROSOFT_AZURE_USE_FOR_DEFAULT_UPLOAD to override it.

Even as a WordPress engineer, I am not sure how to interpret this. Does "Upload tab" refer to the "Upload Files" tab in the media uploader when I'm creating the post? If I check this box, will Azure storage be used there but not in `wp-admin/upload.php`? What about in `wp-admin/media-new.php`? 

When I don't have this box checked, does it effectively mean that Azure is only used when I access it through this "Add Media from Azure" button?

<img width="596" alt="Screen Shot 2019-10-24 at 9 55 07 PM" src="https://user-images.githubusercontent.com/9020968/67539834-f95bea80-f6a8-11e9-8845-dbc8a037c839.png">

Outside of the screen brought up by that button, it's hard to know when I am uploading to Azure and when I'm not.

**Describe the solution you'd like**

The plugin should provide more clarity around this setting. The "Upload tab" language is the main point of confusion, but there should also be something to address what happens in `wp-admin/uploads.php` and in other locations outside the post editor, and perhaps something in the UI wherever we are uploading to Azure to make that apparent.

**Designs**

**Describe alternatives you've considered**

**Additional context**

Testing for the purposes of https://github.com/10up/classifai/pull/149, though that PR doesn't depend on this.

I'd be happy to submit a PR for this, but first I would need to understand more about how the plugin works.

**Comment by rickalee** [comment]
@johnwatkins0 

In my experience, we typically enable 'Use Microsoft Azure Storage when uploading via WordPress' upload tab'. This does take over for all Media uploads including 'Add Media' modals and Media > Add New - media-new.php 

If this option is not checked, you can upload to Azure only through 'Add Media from Azure'

**Comment by johnwatkins0** [comment]
So then maybe, "Use Microsoft Azure Storage for all media uploads," would be more accurate.
